INSERT INTO survey (
    company_id,
    index,
    q_id,
    q_dimension_id,
    q_text,
    q_category
) VALUES
($1, '1', 'S35', $2, 'I have the tools and resources I need to do my job well.', null), 
($1, '2', 'S33', $2, 'I have received the training I need to do my job well.', null), 
($1, '3', 'S97', $2, 'The amount of work I am expected to do is reasonable.', null), 
($1, '4', 'S34', $2, 'I have the freedom to choose how to best perform my job.', 'Autonomy'), 
($1, '5', 'S28', $2, 'I feel that I can share my ideas and opinions without fear of negative consequences.', null), 
($1, '6', 'S23', $2, 'I feel challenged and stretched in my job in a way that results in personal growth.', 'Growth'), 
($1, '7', 'S48', $2, 'Most days, I feel like I am making progress on important work projects or initiatives.', 'Impact'), 
($1, '8', 'S99', $2, 'The level of stress in my job is manageable.', null), 
($1, '9', 'S30', $2, 'I enjoy the day-to-day work I perform.', 'Connection'), 
($1, '10', 'S56', $2, 'My job provides me with a sense of meaning and purpose.', 'Meaning'), 
($1, '11', 'S47', $2, 'It is easy to become absorbed in my job.', 'Engagement Anchor'), 
($1, '12', 'S79', $2, 'My work is valued by this organization.', null), 
($1, '13', 'S49', $2, 'Most days, I look forward to coming to work.', 'Engagement Anchor'), 
($1, '14', 'S84', $2, 'Overall, I love my job.', 'Engagement Anchor'), 
($1, '15', 'S59', $4, 'My supervisor communicates important information to the team.', null), 
($1, '16', 'S19', $4, 'I clearly understand what my supervisor expects of me.', null), 
($1, '17', 'S62', $4, 'My supervisor gives me ongoing feedback about my performance.', null), 
($1, '18', 'S74', $4, 'My supervisor treats people with fairness and respect.', null), 
($1, '19', 'S60', $4, 'My supervisor creates a positive and energizing workplace.', null), 
($1, '20', 'S142', $4, 'My supervisor helps me align my own goals with the work that I do.', 'Meaning'), 
($1, '21', 'S143', $4, 'My supervisor empowers me to get my work done in the way I see best.', 'Autonomy'), 
($1, '22', 'S70', $4, 'My supervisor regularly recognizes my efforts and contributions.', 'Impact'), 
($1, '23', 'S73', $4, 'My supervisor supports my efforts to develop and grow.', 'Growth'), 
($1, '24', 'S38', $4, 'I trust my supervisor.', null), 
($1, '25', 'S139', $4, 'My supervisor cares about me as a person.', 'Connection'), 
($1, '26', 'S103', $3, 'The people I work with treat me with respect.', null), 
($1, '27', 'S104', $3, 'The people on my team collaborate and help each other.', null), 
($1, '28', 'S102', $3, 'The people I work with take accountability for results.', null), 
($1, '29', 'S127', $3, 'We listen to and value each others'' thoughts and opinions.', null), 
($1, '30', 'S9', $3, 'I am empowered to make improvements within our team.', 'Autonomy'), 
($1, '31', 'DW1', $3, 'Our team openly shares innovative and creative ideas with each other.', null), 
($1, '32', 'S144', $3, 'As a team, we help each other improve.', 'Growth'), 
($1, '33', 'S145', $3, 'I see a clear link between our team''s efforts and the success of the organization.', 'Impact'), 
($1, '34', 'S22', $3, 'I enjoy working with the people on my team.', 'Connection'), 
($1, '35', 'S146', $3, 'Our team is proud of the work we do.', 'Meaning'), 
($1, '36', 'S129', $5, 'We work effectively across departments and functions.', null), 
($1, '37', 'S42', $5, 'I understand the vision and goals of this organization.', null), 
($1, '38', 'S107', $5, 'The vision and goals of this organization are important to me personally.', 'Meaning'), 
($1, '39', 'S41', $5, 'I understand how my work contributes to the overall success of this organization.', 'Impact'), 
($1, '40', 'S17', $5, 'I am satisfied with the opportunities for my own professional growth in this organization.', 'Growth'), 
($1, '41', 'S25', $5, 'I feel like I belong here.', 'Connection'), 
($1, '42', 'S115', $5, 'This organization communicates effectively with all employees about what is going on.', null), 
($1, '43', 'S121', $5, 'This organization values employee input, feedback, and suggestions.', null), 
($1, '44', 'S95', $5, 'Senior leaders have a clear understanding of what is going on in the organization.', null), 
($1, '45', 'S147', $5, 'This organization trusts its employees to do their jobs.', 'Autonomy'), 
($1, '46', 'S118', $5, 'This organization is responsive to ideas and suggestions for improvement.', null), 
($1, '47', 'S148', $5, 'I feel comfortable in this organization''s culture.', 'Connection'), 
($1, '48', 'S114', $5, 'This organization cares about employees.', null), 
($1, '49', 'S7', $5, 'I am confident that this organization has a successful future.', null), 
($1, '50', 'S43', $5, 'I would choose to remain with this organization, even if a job with similar pay and benefits were available elsewhere.', 'Engagement Anchor'), 
($1, '51', 'S44', $5, 'I would recommend this organization as a great place to work.', 'Engagement Anchor');