INSERT INTO survey (
    company_id,
    q_id,
    q_dimension_id,
    q_text,
    q_category
) VALUES
($1, 'S35', '1', '1. I have the tools and resources I need to do my job well.', 'null'), 
($1, 'S33', '1', '2. I have received the training I need to do my job well.', 'null'), 
($1, 'S97', '1', '3. The amount of work I am expected to do is reasonable.', 'null'), 
($1, 'S34', '1', '4. I have the freedom to choose how to best perform my job.', 'Autonomy'), 
($1, 'S28', '1', '5. I feel that I can share my ideas and opinions without fear of negative consequences.', 'null'), 
($1, 'S23', '1', '6. I feel challenged and stretched in my job in a way that results in personal growth.', 'Growth'), 
($1, 'S48', '1', '7. Most days, I feel like I am making progress on important work projects or initiatives.', 'Impact'), 
($1, 'S99', '1', '8. The level of stress in my job is manageable.', 'null'), 
($1, 'S30', '1', '9. I enjoy the day-to-day work I perform.', 'Connection'), 
($1, 'S56', '1', '10. My job provides me with a sense of meaning and purpose.', 'Meaning'), 
($1, 'S47', '1', '11. It is easy to become absorbed in my job.', 'Engagement Anchor'), 
($1, 'S79', '1', '12. My work is valued by this organization.', 'null'), 
($1, 'S49', '1', '13. Most days, I look forward to coming to work.', 'Engagement Anchor'), 
($1, 'S84', '1', '14. Overall, I love my job.', 'Engagement Anchor'), 
($1, 'S59', '3', '15. My supervisor communicates important information to the team.', 'null'), 
($1, 'S19', '3', '16. I clearly understand what my supervisor expects of me.', 'null'), 
($1, 'S62', '3', '17. My supervisor gives me ongoing feedback about my performance.', 'null'), 
($1, 'S74', '3', '18. My supervisor treats people with fairness and respect.', 'null'), 
($1, 'S60', '3', '19. My supervisor creates a positive and energizing workplace.', 'null'), 
($1, 'S142', '3', '20. My supervisor helps me align my own goals with the work that I do.', 'Meaning'), 
($1, 'S143', '3', '21. My supervisor empowers me to get my work done in the way I see best.', 'Autonomy'), 
($1, 'S70', '3', '22. My supervisor regularly recognizes my efforts and contributions.', 'Impact'), 
($1, 'S73', '3', '23. My supervisor supports my efforts to develop and grow.', 'Growth'), 
($1, 'S38', '3', '24. I trust my supervisor.', 'null'), 
($1, 'S139', '3', '25. My supervisor cares about me as a person.', 'Connection'), 
($1, 'S103', '2', '26. The people I work with treat me with respect.', 'null'), 
($1, 'S104', '2', '27. The people on my team collaborate and help each other.', 'null'), 
($1, 'S102', '2', '28. The people I work with take accountability for results.', 'null'), 
($1, 'S127', '2', '29. We listen to and value each others'' thoughts and opinions.', 'null'), 
($1, 'S9', '2', '30. I am empowered to make improvements within our team.', 'Autonomy'), 
($1, 'DW1', '2', '31. Our team openly shares innovative and creative ideas with each other.', 'null'), 
($1, 'S144', '2', '32. As a team, we help each other improve.', 'Growth'), 
($1, 'S145', '2', '33. I see a clear link between our team''s efforts and the success of the organization.', 'Impact'), 
($1, 'S22', '2', '34. I enjoy working with the people on my team.', 'Connection'), 
($1, 'S146', '2', '35. Our team is proud of the work we do.', 'Meaning'), 
($1, 'S129', '4', '36. We work effectively across departments and functions.', 'null'), 
($1, 'S42', '4', '37. I understand the vision and goals of this organization.', 'null'), 
($1, 'S107', '4', '38. The vision and goals of this organization are important to me personally.', 'Meaning'), 
($1, 'S41', '4', '39. I understand how my work contributes to the overall success of this organization.', 'Impact'), 
($1, 'S17', '4', '40. I am satisfied with the opportunities for my own professional growth in this organization.', 'Growth'), 
($1, 'S25', '4', '41. I feel like I belong here.', 'Connection'), 
($1, 'S115', '4', '42. This organization communicates effectively with all employees about what is going on.', 'null'), 
($1, 'S121', '4', '43. This organization values employee input, feedback, and suggestions.', 'null'), 
($1, 'S95', '4', '44. Senior leaders have a clear understanding of what is going on in the organization.', 'null'), 
($1, 'S147', '4', '45. This organization trusts its employees to do their jobs.', 'Autonomy'), 
($1, 'S118', '4', '46. This organization is responsive to ideas and suggestions for improvement.', 'null'), 
($1, 'S148', '4', '47. I feel comfortable in this organization''s culture.', 'Connection'), 
($1, 'S114', '4', '48. This organization cares about employees.', 'null'), 
($1, 'S7', '4', '49. I am confident that this organization has a successful future.', 'null'), 
($1, 'S43', '4', '50. I would choose to remain with this organization, even if a job with similar pay and benefits were available elsewhere.', 'Engagement Anchor'), 
($1, 'S44', '4', '51. I would recommend this organization as a great place to work.', 'Engagement Anchor');

